import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/header";
import Navigation from "@/components/layouts/Navigation";
import Footer from "@/components/layouts/footer";
import ReactQueryProvider from "@/provider/react-query";
import { Toaster } from "@/components/ui/sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Francis-demo-E-commerce-store ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jost.className}   antialiased`}
        suppressHydrationWarning
      >
        <Toaster position="top-center" />

        <ReactQueryProvider>
          <Header />
          <Navigation />
          <div className="min-h-screen ">{children}</div>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
